const ALERT_TYPES = {
  SCORE_CHANGE: 'score_change',
  LOAN_OVERDUE: 'loan_overdue',
  INSURANCE_EXPIRY: 'insurance_expiry',
  PM_KISAN_PENDING: 'pm_kisan_pending',
  WEATHER_RISK: 'weather_risk',
  SCHEME_OPPORTUNITY: 'scheme_opportunity',
  OFFICER_CALLBACK: 'officer_callback',
  CUSTOM: 'custom'
}

const ALERT_PRIORITIES = {
  URGENT: 'urgent',
  HIGH: 'high',
  MEDIUM: 'medium',
  LOW: 'low'
}

const ALERT_PRIORITY_MAP = {
  [ALERT_TYPES.SCORE_CHANGE]: ALERT_PRIORITIES.URGENT,
  [ALERT_TYPES.LOAN_OVERDUE]: ALERT_PRIORITIES.URGENT,
  [ALERT_TYPES.INSURANCE_EXPIRY]: ALERT_PRIORITIES.HIGH,
  [ALERT_TYPES.PM_KISAN_PENDING]: ALERT_PRIORITIES.MEDIUM,
  [ALERT_TYPES.WEATHER_RISK]: ALERT_PRIORITIES.HIGH,
  [ALERT_TYPES.SCHEME_OPPORTUNITY]: ALERT_PRIORITIES.MEDIUM,
  [ALERT_TYPES.OFFICER_CALLBACK]: ALERT_PRIORITIES.HIGH,
  [ALERT_TYPES.CUSTOM]: ALERT_PRIORITIES.LOW
}

const ALERT_DEDUP_WINDOWS = {
  [ALERT_TYPES.SCORE_CHANGE]: '24 hours',
  [ALERT_TYPES.LOAN_OVERDUE]: '7 days',
  [ALERT_TYPES.INSURANCE_EXPIRY]: '3 days',
  [ALERT_TYPES.PM_KISAN_PENDING]: '14 days',
  [ALERT_TYPES.WEATHER_RISK]: '6 hours',
  [ALERT_TYPES.SCHEME_OPPORTUNITY]: '7 days',
  [ALERT_TYPES.OFFICER_CALLBACK]: '24 hours',
  [ALERT_TYPES.CUSTOM]: '24 hours'
}

module.exports = {
  ALERT_TYPES,
  ALERT_PRIORITIES,
  ALERT_PRIORITY_MAP,
  ALERT_DEDUP_WINDOWS
}
